[project]
name = "deepvqe"
version = "0.1.0"
description = "DeepVQE model implementation with Torch inference utilities"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "einops==0.8.0",
    "numpy==2.3.5",
    "onnx==1.17.0",
    "onnxruntime==1.19.2",
    "onnxsim==0.4.36",
    "ptflops==0.7.3",
    "pydantic>=2.12.5",
    "soundfile>=0.13.1",
    "torch==2.9.1",
    "tqdm>=4.67.1",
]

[tool.uv]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[tool.uv.sources]
torch = [{ index = "pytorch-cu130", marker = "sys_platform == 'linux' or sys_platform == 'win32'" }]
torchvision = [{ index = "pytorch-cu130", marker = "sys_platform == 'linux' or sys_platform == 'win32'" }]
torchaudio = [{ index = "pytorch-cu130", marker = "sys_platform == 'linux' or sys_platform == 'win32'" }]

